Dump .vv file.

diff --git a/tools/test-console b/tools/test-console
--- a/tools/test-console
+++ b/tools/test-console
@@ -160,7 +160,19 @@ echo -e "${H1}==================================================${Color_Off}"
 echo -e "${H1}Attempt to fetch a .vv file from Kerbside${Color_Off}"
 echo -e "${H1}==================================================${Color_Off}"
 
-curl --cacert /etc/kolla/certificates/ca/root.crt ${consoleurl}
+curl --cacert /etc/kolla/certificates/ca/root.crt \
+    --output /tmp/console.vv ${consoleurl}
+
+echo
+echo -e "${H1}==================================================${Color_Off}"
+echo -e "${H1}Dump .vv file${Color_Off}"
+echo -e "${H1}==================================================${Color_Off}"
+if [ ! -e /tmp/console.vv ]; then
+    echo "Console file missing!"
+    exit 1
+fi
+
+cat /tmp/console.vv
 
 trap - EXIT
 
